src/SoCFeedback/Controllers/LevelsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SoCFeedback.Data;
using SoCFeedback.Enums;
using SoCFeedback.Models;

namespace SoCFeedback.Controllers
{
    [Authorize(Roles = "Admin")]
    public class LevelsController : Controller
    {
        private readonly FeedbackDbContext _context;

        public LevelsController(FeedbackDbContext context)
        {
            _context = context;
        }

        // GET: Levels
        public async Task<IActionResult> Index()
        {
            return View(await _context.Level.ToListAsync());
        }

        // GET: Levels/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
                return NotFound();

            var level = await _context.Level
                .SingleOrDefaultAsync(m => m.Id == id);
            if (level == null)
                return NotFound();

            return View(level);
        }

        // GET: Levels/Create
        public IActionResult Create()
        {
            return View(new Level{OrderingNumber = _context.Level.Max(c => c.OrderingNumber) + 1 });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Status,Description,OrderingNumber")] Level level)
        {
            var obj = _context.Level.Any(e => e.Title.Equals(level.Title, StringComparison.OrdinalIgnoreCase));
            if (obj)
                ModelState.AddModelError("Title", string.Format("Level {0} already exists.", level.Title));

            if (ModelState.IsValid)
            {
                level.Id = Guid.NewGuid();
                _context.Add(level);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(level);
        }

        // GET: Levels/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
                return NotFound();

            var level = await _context.Level.SingleOrDefaultAsync(m => m.Id == id);
            if (level == null)
                return NotFound();
            return View(level);
        }

        // POST: Levels/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Title,Status,Description,OrderingNumber")] Level level)
        {
            if (id != level.Id)
                return NotFound();

            var obj =
                await _context.Level.SingleOrDefaultAsync(
                    e => e.Title.Equals(level.Title, StringComparison.OrdinalIgnoreCase) && e.Id != level.Id);
            if (obj != null)
                ModelState.AddModelError("Title", string.Format("Level {0} already exists.", level.Title));

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(level);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LevelExists(level.Id))
                        return NotFound();
                    throw;
                }
                return RedirectToAction("Index");
            }
            return View(level);
        }

        // GET: Levels/Archive/5
        public async Task<IActionResult> Archive(Guid? id)
        {
            if (id == null)
                return NotFound();

            var level = await _context.Level
                .SingleOrDefaultAsync(m => m.Id == id);
            if (level == null)
                return NotFound();

            return View(level);
        }

        // POST: Levels/Archive/5
        [HttpPost]
        [ActionName("Archive")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ArchiveConfirmed(Guid id)
        {
            var level = await _context.Level.SingleOrDefaultAsync(m => m.Id == id);
            if (level == null)
                return NotFound();
            level.Status = Status.Archived;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // GET: Categories/Restore/5
        public async Task<IActionResult> Restore(Guid? id)
        {
            if (id == null)
                return NotFound();

            var level = await _context.Level
                .SingleOrDefaultAsync(m => m.Id == id);
            if (level == null)
                return NotFound();

            return View(level);
        }

        // POST: Categories/Restore/5
        [HttpPost]
        [ActionName("Restore")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RestoreConfirmed(Guid id)
        {
            var level = await _context.Level.SingleOrDefaultAsync(m => m.Id == id);
            if (level == null)
                return NotFound();
            level.Status = Status.Active;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool LevelExists(Guid id)
        {
            return _context.Level.Any(e => e.Id == id);
        }
    }
}

src/SoCFeedback/Controllers/ModulesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SoCFeedback.Data;
using SoCFeedback.Enums;
using SoCFeedback.Models;
using SoCFeedback.Models.ViewModels;

namespace SoCFeedback.Controllers
{
    [Authorize(Roles = "Admin,Lecturer,LecturerLimited,TeachingStaff")]
    public class ModulesController : Controller
    {
        private readonly FeedbackDbContext _context;

        public ModulesController(FeedbackDbContext context)
        {
            _context = context;
        }
        [Authorize(Roles = "Admin,Lecturer,LecturerLimited")]
        // GET: Modules
        public async Task<IActionResult> Index()
        {
            var feedbackDbContext = _context.Module.Include(l => l.Level).Include(s => s.Supervisor);
            return View(await feedbackDbContext.ToListAsync());
        }

        // GET: Modules/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
                return NotFound();

            var module = await _context.Module
                .Include(l => l.Level)
                .Include(s => s.Supervisor)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (module == null)
                return NotFound();
            return View(module);
        }

        // GET: Modules/Create
        [Authorize(Roles = "Admin,Lecturer,LecturerLimited")]
        public IActionResult Create()
        {
            ViewData["LevelId"] = new SelectList(_context.Level.OrderBy(o => o.OrderingNumber).AsNoTracking().Where(s => s.Status == Status.Active), "Id", "Title");
            ViewData["SupervisorId"] = new SelectList(_context.Supervisor.OrderBy(o => o.Forename).AsNoTracking().Where(s => s.Status == Status.Active), "Id", "FullName");
            return View(new Module());
        }

        // POST: Modules/Create
        [Authorize(Roles = "Admin,Lecturer,LecturerLimited")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("Id,Code,Title,Url,LevelId,SupervisorId,Description,Status")] Module module)
        {
            var obj = _context.Module.Any(e => e.Code.Equals(module.Code, StringComparison.OrdinalIgnoreCase));
            if (obj)
                ModelState.AddModelError("Code", string.Format("Module with code {0} already exists.", module.Code));

            if (ModelState.IsValid)
            {
                module.Id = Guid.NewGuid();
                _context.Add(module);
                await AddQuestions(module);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["LevelId"] = new SelectList(_context.Level.OrderBy(o => o.OrderingNumber).AsNoTracking().Where(s => s.Status == Status.Active), "Id", "Title",
                module.LevelId);
            ViewData["SupervisorId"] = new SelectList(_context.Supervisor.OrderBy(o => o.Forename).AsNoTracking().Where(s => s.Status == Status.Active), "Id", "FullName",
                module.SupervisorId);
            return View(module);
        }

        // GET: Modules/Edit/5
        [Authorize(Roles = "Admin,Lecturer,LecturerLimited")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
                return NotFound();

            var module = await _context.Module.SingleOrDefaultAsync(m => m.Id == id);
            if (module == null)
                return NotFound();

            SetLevelAndSupervisorList(module);
            return View(module);
        }

        // POST: Modules/Edit/5
        [Authorize(Roles = "Admin,Lecturer,LecturerLimited")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id,
            [Bind("Id,Code,Title,Url,LevelId,SupervisorId,Description,Status")] Module module)
        {
            if (id != module.Id)
                return NotFound();

            var obj =
                _context.Module.Any(
                    e => e.Code.Equals(module.Code, StringComparison.OrdinalIgnoreCase) && e.Id != module.Id);
            if (obj)
                ModelState.AddModelError("Code", string.Format("Module with code {0} already exists.", module.Code));

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(module);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ModuleExists(module.Id))
                        return NotFound();
                    throw;
                }
                return RedirectToAction("Index");
            }

            SetLevelAndSupervisorList(module);
            return View(module);
        }

        private void SetLevelAndSupervisorList(Module module)
        {
            ViewData["LevelId"] = new SelectList(_context.Level.OrderBy(o => o.OrderingNumber).AsNoTracking()
                .Where(s => s.Status == Status.Active || s.Id == module.LevelId), "Id", "Title",
                module.LevelId);
            ViewData["SupervisorId"] = new SelectList(_context.Supervisor.OrderBy(o => o.Forename).AsNoTracking()
                .Where(s => s.Status == Status.Active || s.Id == module.SupervisorId), "Id", "FullName",
                module.SupervisorId);
        }

        // GET: Modules/Archive/5
        [Authorize(Roles = "Admin,Lecturer,LecturerLimited")]
        public async Task<IActionResult> Archive(Guid? id)
        {
            if (id == null)
                return NotFound();

            var module = await _context.Module
                .Include(l => l.Level)
                .Include(s => s.Supervisor)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (module == null)
                return NotFound();

            return View(module);
        }

        // POST: Modules/Archive/5
        [Authorize(Roles = "Admin,Lecturer")]
        [HttpPost]
        [ActionName("Archive")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ArchiveConfirmed(Guid id)
        {
            var module = await _context.Module.SingleOrDefaultAsync(m => m.Id == id);
            module.Status = Status.Archived;

            // remove module that is being archived from pending academic year forms
            var yearModules = _context.YearModules.Where(m => m.ModuleId == module.Id && m.YearNavigation.Status == YearStatus.Pending);
            if (yearModules != null)
            {
                foreach (var ymodule in yearModules)
                {
                    _context.YearModules.Remove(ymodule);
                }
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // GET: Modules/Restore/5
        [Authorize(Roles = "Admin,Lecturer")]
        public async Task<IActionResult> Restore(Guid? id)
        {
            if (id == null)
                return NotFound();

            var module = await _context.Module
                .Include(l => l.Level)
                .Include(s => s.Supervisor)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (module == null)
                return NotFound();

            return View(module);
        }

        // POST: Modules/Restore/5
        [Authorize(Roles = "Admin,Lecturer")]
        [HttpPost]
        [ActionName("Restore")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RestoreConfirmed(Guid id)
        {
            var module = await _context.Module.SingleOrDefaultAsync(m => m.Id == id);
            module.Status = Status.Active;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // GET: Modules/Questions/5
        [Authorize(Roles = "Admin,Lecturer,LecturerLimited")]
        public async Task<IActionResult> Questions(Guid? id, Guid yid)
        {
            if (id == null)
                return NotFound();
            var module = await _context.Module.AsNoTracking()
                .Include(l => l.Level)
                .Include(s => s.Supervisor)
                .Include(q => q.ModuleQuestions)
                .SingleOrDefaultAsync(m => m.Id == id);

            var year = await _context.Year.AsNoTracking().SingleOrDefaultAsync(y => y.Id == yid);
            if (module == null || year == null)
                return NotFound();

            if (year.Status != YearStatus.Pending)
            {
                return NotFound();
            }

            module.Questions = _context.Question.Include(c => c.Category)
                .AsNoTracking()
                .Where(q => q.Status == Status.Active && q.Category.Status == Status.Active)
                .OrderBy(q => q.QuestionNumber)
                .ToList();

            //remove questions not belonging to a module
            foreach (var question in module.Questions)
                if (!module.ModuleQuestions.Exists(m => m.QuestionId == question.Id))
                    question.RunningStatus = RunningStatus.Inactive;

            module.YearId = yid;
            var tempCategory = module.Questions.Select(m => m.Category).ToList();
            module.Categories =
                tempCategory.GroupBy(e => e.Title).Select(group => group.First()).OrderBy(e => e.CategoryOrder).ToList();


            return View(module);
        }

        // POST: Modules/Questions/5
        [Authorize(Roles = "Admin,Lecturer,LecturerLimited")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Questions(Guid? id, [Bind("Id,Questions,Categories,YearId")] Module module)
        {

src/SoCFeedback/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
@inject SignInManager<ApplicationUser> SignInManager
@{
    string pagename = ((Microsoft.AspNetCore.Mvc.Controllers.ControllerActionDescriptor)ViewContext.ActionDescriptor).ActionName;
    string controllerName = ((Microsoft.AspNetCore.Mvc.Controllers.ControllerActionDescriptor)ViewContext.ActionDescriptor).ControllerName;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Computing Feedback</title>
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
        <script src="~/lib/chartist/dist/chartist.js" asp-append-version="true"></script>
        <script src="~/lib/chartist-plugin-axistitle/dist/chartist-plugin-axistitle.js" asp-append-version="true"></script>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/datatables/media/css/dataTables.bootstrap4.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/bootstrap-star-rating/css/star-rating.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/bootstrap-star-rating/css/theme-krajee-fa.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/chartist/dist/chartist.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
        @if (pagename.Equals("Index") && !controllerName.Equals("Home"))
        {
            <link rel="stylesheet" href="~/lib/datatables/media/css/dataTables.bootstrap4.min.css" asp-append-version="true" />
        }
        @if (pagename.Equals("Module") || pagename.Equals("Feedback"))
        {
            <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" asp-append-version="true" />
            <link rel="stylesheet" href="~/lib/bootstrap-star-rating/css/star-rating.min.css" asp-append-version="true" />
            <link rel="stylesheet" href="~/lib/bootstrap-star-rating/css/theme-krajee-fa.min.css" asp-append-version="true" />
            if (pagename.Equals("Feedback"))
            {
                <link rel="stylesheet" href="~/lib/chartist/dist/chartist.min.css" asp-append-version="true" />
                <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
                <script src="~/lib/chartist/dist/chartist.min.js" asp-append-version="true"></script>
                <script src="~/lib/chartist-plugin-axistitle/dist/chartist-plugin-axistitle.min.js" asp-append-version="true"></script>
            }
        }
        @if (pagename.Equals("Create") || pagename.Equals("Edit") && !controllerName.Equals("Years"))
        {
            <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
        }
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar bg-inverse navbar-dark navbar-toggleable-sm">
        <div class="container-fluid">
            <button class="navbar-toggler hidden-md-up float-xs-right " type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"></button>
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
                <img src="/favicon.ico" width="30" height="30" class="d-inline-block align-top" alt="SoC logo">
                Computing Feedback
            </a>
            <div class="collapse navbar-toggleable-sm " id="navbarSupportedContent">
                <ul class="nav navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">About</a>
                    </li>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        if (!await AuthorizationService.AuthorizeAsync(User, "TeachingStaff"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" title="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Entities
                                </a>
                                <ul class="dropdown-menu bg-inverse" aria-labelledby="navbarDropdownMenuLink">
                                    @if (await AuthorizationService.AuthorizeAsync(User, "Admin"))
                                    {
                                        <li>
                                            <a class="dropdown-item link " asp-area="" asp-controller="Categories" asp-action="Index" title="Categories">Categories</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item link" asp-area="" asp-controller="Levels" asp-action="Index" title="Levels">Levels</a>
                                        </li>
                                    }
                                    <li>
                                        <a class="dropdown-item link" asp-area="" asp-controller="Questions" asp-action="Index" title="Questions">Questions</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item link" asp-area="" asp-controller="Supervisors" asp-action="Index" title="Supervisors">Supervisors</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item link" asp-area="" asp-controller="Modules" asp-action="Index" title="Modules">Modules</a>
                                    </li>
                                </ul>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Years" asp-action="Index" title="Years">Years</a>
                        </li>
                        if (await AuthorizationService.AuthorizeAsync(User, "Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Index" title="Staff Accounts">Staff Accounts</a>
                            </li>
                        }
                    }
                    @await Html.PartialAsync("_LoginPartial")
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
        <hr />
        <footer class="text-xs-center">
            <p>
                Please email <a href="mailto:a.taraskevicius@dundee.ac.uk"> Aistis Taraskevicius</a> if you've encountered problems or have feedback.
            </p>
        </footer>
    </div>
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js" asp-append-version="true"></script>
        <script src="~/lib/datatables/media/js/jquery.dataTables.js" asp-append-version="true"></script>
        <script src="~/lib/datatables/media/js/datatables.bootstrap4.js" asp-append-version="true"></script>
        <script src="~/lib/textarea-autosize/dist/jquery.textarea_autosize.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap-star-rating/js/star-rating.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap-star-rating/themes/krajee-fa/theme.js" asp-append-version="true"></script>
    </environment>
<environment names="Staging,Production">
    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    @if (!(pagename.Equals("Index") && controllerName.Equals("Home")) && !pagename.Equals("About"))
    {
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
        <script src="~/lib/textarea-autosize/dist/jquery.textarea_autosize.min.js" asp-append-version="true"></script>
        <script type="text/javascript">$(document).ready(function() { $(".autosize").textareaAutoSize(); });</script>
        <script type="text/javascript">window.addEventListener('resize', go); function go() { $('.autosize').trigger('input');}</script>
    }
    @if (pagename.Equals("Index") && !controllerName.Equals("Home"))
    {
        <script src="~/lib/datatables/media/js/jquery.dataTables.min.js" asp-append-version="true"></script>
        <script src="~/lib/datatables/media/js/dataTables.bootstrap4.min.js" asp-append-version="true"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                $('#YearTable').DataTable({ "order": [[0, "desc"]] });
                $(".table").DataTable();
            });
        </script>
    }
    @if (pagename.Equals("Module") || pagename.Equals("Feedback"))
    {
        <script src="~/lib/bootstrap-star-rating/js/star-rating.min.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap-star-rating/themes/krajee-fa/theme.min.js" asp-append-version="true"></script>
    }
</environment>
    @RenderSection("scripts", false)
</body>
</html>