src/SoCFeedback/Models/Module.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using SoCFeedback.Enums;

namespace SoCFeedback.Models
{
    public class Module
    {
        public Module()
        {
            ModuleQuestions = new List<ModuleQuestions>();
            YearModules = new HashSet<YearModules>();
        }

        /// <summary>
        /// Module ID
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Module Code
        /// </summary>
        [Required]
        [StringLength(Constants.ModuleCodeLength)]
        public string Code { get; set; }

        /// <summary>
        /// Module Title
        /// </summary>
        [Required]
        [StringLength(Constants.ModuleTitleLength)]
        public string Title { get; set; }

        /// <summary>
        /// Module URL
        /// </summary>
        [StringLength(Constants.UrlLength)]
        [Url]
        [Display(Name = "Module URL")]
        public string Url { get; set; }

        /// <summary>
        /// Level ID the module belongs to
        /// </summary>
        [Required]
        public Guid LevelId { get; set; }

        /// <summary>
        /// Supervisor ID, that supervises the Module
        /// </summary>
        [Required]
        public Guid SupervisorId { get; set; }

        /// <summary>
        /// Module Description
        /// </summary>
        [StringLength(Constants.ModuleDescLength)]
        public string Description { get; set; }

        /// <summary>
        /// Module Status
        /// </summary>
        public Status Status { get; set; }

        /// <summary>
        /// Module running status within an academic year, not mapped to the database
        /// </summary>
        [NotMapped]
        public RunningStatus RunningStatus { get; set; }

        /// <summary>
        /// Module year ID, not mapped to the database
        /// </summary>
        [NotMapped]
        public Guid YearId { get; set; }

        /// <summary>
        /// List of module questions, not mapped to the database
        /// </summary>
        [NotMapped]
        public List<Question> Questions { get; set; }

        /// <summary>
        /// Module questions categories, not mapped to the database
        /// </summary>
        [NotMapped]
        public List<Category> Categories { get; set; }

        /// <summary>
        /// Virtual list of the module questions
        /// </summary>
        public virtual List<ModuleQuestions> ModuleQuestions { get; set; }
        
        /// <summary>
        /// Virtual list of year modules
        /// </summary>
        public virtual ICollection<YearModules> YearModules { get; set; }

        /// <summary>
        /// Virtual module level object
        /// </summary>
        public virtual Level Level { get; set; }

        /// <summary>
        /// Virtual module supervisor object
        /// </summary>
        [Display(Name = "Coordinator")]
        public virtual Supervisor Supervisor { get; set; }

        /// <summary>
        /// Module code and title combined
        /// </summary>
        [Display(Name = "Module")]
        [NotMapped]
        public string ModuleName => $"{Code} {Title}";
    }
}

src/SoCFeedback/Models/Question.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using SoCFeedback.Enums;

namespace SoCFeedback.Models
{
    public class Question
    {
        public Question()
        {
            ModuleQuestions = new HashSet<ModuleQuestions>();
            Answer = new HashSet<Answer>();
            RateAnswer = new HashSet<RateAnswer>();
        }

        /// <summary>
        /// Question ID
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Question Text
        /// </summary>
        [Display(Name = "Question")]
        [Required]
        [StringLength(Constants.QuestionLength)]
        public string Question1 { get; set; }

        /// <summary>
        /// Question Type
        /// </summary>
        [Required]
        public QuestionType Type { get; set; }

        /// <summary>
        /// Category ID the question belongs to
        /// </summary>
        [Required]
        [Display(Name = "Category")]
        public Guid CategoryId { get; set; }

        /// <summary>
        /// Question optionality status
        /// </summary>
        [Display(Name = "Optional")]
        public bool Optional { get; set; } = true;

        /// <summary>
        /// Question status
        /// </summary>
        public Status Status { get; set; }

        /// <summary>
        /// Question Order
        /// </summary>
        [RegularExpression("([0-9]+)", ErrorMessage = "Please enter valid Number")]
        [Display(Name = "Question Order in the Category")]
        public int QuestionNumber { get; set; } = 99;

        [NotMapped]
        public RunningStatus RunningStatus { get; set; }

        /// <summary>
        /// Question answer to save, not mapped to database
        /// </summary>
        [NotMapped]
        public Answer AnswerToSave { get; set; }

        /// <summary>
        /// Rating question answer to save, not mapped to database
        /// </summary>
        [NotMapped]
        public RateAnswer RateAnswerToSave { get; set; }

        /// <summary>
        /// Year status, not mapped to database
        /// </summary>
        [NotMapped]
        public bool YearPublished { get; set; }

        /// <summary>
        /// Virtual list of Module questions
        /// </summary>
        public virtual ICollection<ModuleQuestions> ModuleQuestions { get; set; }

        /// <summary>
        /// Virtual list of question answers
        /// </summary>
        public virtual ICollection<Answer> Answer { get; set; }

        /// <summary>
        /// Virtual list of rating type question answers
        /// </summary>
        public virtual ICollection<RateAnswer> RateAnswer { get; set; }

        /// <summary>
        /// Virtual category object
        /// </summary>
        public virtual Category Category { get; set; }
    }
}

src/SoCFeedback/Controllers/YearsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SoCFeedback.Data;
using SoCFeedback.Enums;
using SoCFeedback.Models;

namespace SoCFeedback.Controllers
{
    [Authorize(Roles = "Admin,Lecturer,LecturerLimited,TeachingStaff")]
    public class YearsController : Controller
    {
        private readonly FeedbackDbContext _context;

        public YearsController(FeedbackDbContext context)
        {
            _context = context;
        }

        // GET: Years
        public async Task<IActionResult> Index()
        {
            return View(await _context.Year.ToListAsync());
        }

        // GET: Years/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
                return NotFound();

            var year =
                await _context.Year.Include(y => y.YearModules).AsNoTracking().SingleOrDefaultAsync(m => m.Id == id);

            if (year == null)
                return NotFound();

            year.Modules = GetYearModules(year, _context);
            year.Levels = GetYearLevels(year);
            return View(year);
        }

        [Authorize(Roles = "Admin")]
        // GET: Years/Create
        public IActionResult Create()
        {
            var year = new Year
            {
                Modules =
                    _context.Module.Where(m => m.Status == Status.Active && m.Level.Status == Status.Active).OrderBy(o => o.Code).AsNoTracking().ToList(),
                Levels =
                    _context.Level.Where(m => m.Status == Status.Active && m.Module.Count != 0)
                        .OrderBy(o => o.OrderingNumber)
                        .AsNoTracking()
                        .ToList()
            };
            return View(year);
        }

        // POST: Years/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Year1,Status,Modules,Levels")] Year year)
        {
            var obj = _context.Year.Any(e => e.Year1 == year.Year1);
            if (obj)
                ModelState.AddModelError("Year1", $"Academic Year form for year {year.Year1} already exists.");
            if (ModelState.IsValid)
            {
                ArchiveNotArchivedYears();
                var newYear = new Year { Year1 = year.Year1 };
                _context.Add(newYear);

                foreach (var module in year.Modules.Where(m => m.RunningStatus == RunningStatus.Active))
                    _context.YearModules.Add(new YearModules
                    {
                        YearId = newYear.Id,
                        ModuleId = module.Id
                    });
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(year);
        }

        private void ArchiveNotArchivedYears()
        {
            var years = _context.Year.Where(y => y.Status == YearStatus.Published || y.Status == YearStatus.Pending);
            foreach (var year in years)
            {
                year.Status = YearStatus.Archived;
            }
            _context.SaveChanges();
        }

        // GET: Years/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
                return NotFound();

            var year =
                await _context.Year.AsNoTracking().Include(y => y.YearModules).SingleOrDefaultAsync(m => m.Id == id);
            if (year == null)
                return NotFound();
            if (year.Status == YearStatus.Published)
                return RedirectToAction("Index");

            var temptList =
                _context.Module.AsNoTracking()
                    .Include(l => l.Level)
                    .Where(m => m.Status == Status.Active)
                    .OrderBy(o => o.Code)
                    .ToList();

            year.Modules = GetYearModules(year, _context);
            // add new modules that currently don't belong to a year, but are active
            foreach (var module in temptList)
                if (!year.Modules.Exists(m => m.Id == module.Id))
                {
                    module.RunningStatus = RunningStatus.Inactive;
                    year.Modules.Add(module);
                }
            year.Modules = year.Modules.OrderBy(o => o.Code).ToList();
            year.Levels = GetYearLevels(year);

            return View(year);
        }

        // POST: Years/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Year1,Status,Modules,Levels")] Year year)
        {
            if (id != year.Id)
                return NotFound();
            if (year.Status == YearStatus.Published)
                return RedirectToAction("Index");
            var obj = _context.Year.AsNoTracking().Any(e => e.Year1 == year.Year1 && e.Id != year.Id);

            if (obj)
                ModelState.AddModelError("Year1", $"Academic year form for year {year.Year1} already exists.");

            if (!ModelState.IsValid) return View(year);

            try
            {
                var dbYear = await _context.Year.Include(y => y.YearModules).SingleOrDefaultAsync(m => m.Id == id);
                dbYear.Year1 = year.Year1;
                foreach (var module in year.Modules)
                {
                    var tYearModule = new YearModules
                    {
                        YearId = year.Id,
                        ModuleId = module.Id
                    };

                    if (!YearModuleExists(tYearModule) && module.RunningStatus == RunningStatus.Active)
                    {
                        dbYear.YearModules.Add(tYearModule);
                        _context.YearModules.Add(tYearModule);
                    }

                    else if (module.RunningStatus == RunningStatus.Inactive)
                    {
                        var moduleToRemove =
                            dbYear.YearModules.SingleOrDefault(y => y.YearId == year.Id && y.ModuleId == module.Id);
                        if (moduleToRemove != null)
                        {
                            dbYear.YearModules.Remove(moduleToRemove);
                            _context.YearModules.Remove(moduleToRemove);
                        }
                    }
                }
                _context.Update(dbYear);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!YearExists(year.Id))
                    return NotFound();
                throw;
            }
            return RedirectToAction("Index");
        }

        // GET: Years/Publish/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Publish(Guid? id)
        {
            if (id == null)
                return NotFound();

            var year =
                await _context.Year.Include(y => y.YearModules).AsNoTracking().SingleOrDefaultAsync(m => m.Id == id);
            if (year == null)
                return NotFound();
            year.Modules = GetYearModules(year, _context);
            year.Levels = GetYearLevels(year);
            return View(year);
        }

        // POST: Years/Publish/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ActionName("Publish")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PublishConfirmed(Guid id)
        {
            var years = _context.Year.Where(y => y.Status == YearStatus.Published);
            foreach (var dbYear in years)
                dbYear.Status = YearStatus.Archived;

            var year = await _context.Year.SingleOrDefaultAsync(m => m.Id == id);
            year.Status = YearStatus.Published;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // GET: Years/Retract/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Retract(Guid? id)
        {
            if (id == null)
                return NotFound();

            var year =
                await _context.Year.Include(y => y.YearModules).AsNoTracking().SingleOrDefaultAsync(m => m.Id == id);
            if (year == null)
                return NotFound();
            year.Modules = GetYearModules(year, _context);
            year.Levels = GetYearLevels(year);
            return View(year);
        }

        // POST: Years/Retract/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ActionName("Retract")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RetractConfirmed(Guid id)
        {
            var year = await _context.Year.SingleOrDefaultAsync(m => m.Id == id);
            year.Status = YearStatus.Pending;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // GET: Years/Archive/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Archive(Guid? id)
        {
            if (id == null)
                return NotFound();

            var year =
                await _context.Year.Include(y => y.YearModules).AsNoTracking().SingleOrDefaultAsync(m => m.Id == id);
            if (year == null)
                return NotFound();
            year.Modules = GetYearModules(year, _context);
            year.Levels = GetYearLevels(year);
            return View(year);
        }

        // POST: Years/Archive/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ActionName("Archive")]
        [ValidateAntiForgeryToken]

src/SoCFeedback/Views/Modules/Feedback.cshtml
@using Newtonsoft.Json
@using SoCFeedback.Enums
@model SoCFeedback.Models.ViewModels.FeedbackViewModel
@{
    ViewData["Title"] = "Module Feedback";
    var Chart = "chart";
    var Collapse = "Collapse";
}

<div>
    <div>
        <h2>Module Feedback</h2>
        <h4>Module</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Code)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Code)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Level)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Level)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Coordinator)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Coordinator)
            </dd>
        </dl>
    </div>
    <div>
        <hr />
        <h4>Overall Average</h4>
        @if (Model.Average > 0)
        {
            <input data-min="0" data-max="5" data-step="0.1" data-size="md" data-display-only="true" asp-for="@Model.Average" class="rating rating-loading"/>
            <a href="#averageCollapse" data-toggle="collapse" aria-expanded="True" class="font-weight-bold"> Toggle overall average chart </a>
            <div id="averageCollapse" class="collapsing">
                <div class="" id="overallAverage"></div>
            </div>
            <script type="text/javascript">
                new Chartist.Bar('#overallAverage',
                    {
                        labels:
                            @Html.Raw(JsonConvert.SerializeObject(Model.LabelsList)),
                        series: [
                            @Html.Raw(JsonConvert.SerializeObject(Model.RatingsList))
                        ]
                    },
                    {
                        chartPadding: {
                            top: 30,
                            right: 0,
                            bottom: 30,
                            left: 30
                        },
                        stretch: true,
                        height: 400,
                        plugins: [
                            Chartist.plugins.ctAxisTitle({
                                axisX: {
                                    axisTitle: 'Questions',
                                    axisClass: 'font-weight-bold form-control-label',
                                    offset: {
                                        x: 0,
                                        y: 50
                                    },
                                    textAnchor: 'middle'
                                },
                                axisY: {
                                    axisTitle: 'Average',
                                    axisClass: 'font-weight-bold form-control-label',
                                    offset: {
                                        x: 0,
                                        y: -15
                                    },
                                    textAnchor: 'middle',
                                    flipTitle: false
                                }
                            })
                        ]
                    });
            </script>
        }
        else
        {
            <br/>
            <label style="font-size: 26px" class="label label-default">Not Rated</label>
        }
        <hr />
        <h4>Questions</h4>
        <h6>Questions without answers won't be displayed.</h6>
        <hr />
        @for (var j = 0; j < Model.Categories.Count; j++)
            {
            <span class=" text-primary h4 form-text">
                @Html.DisplayFor(m => m.Categories[j].Title)
            </span>
            <ul class="list-group">
                @for (var i = 0; i < Model.Questions.Count; i++)
                {
                    if (Model.Questions[i].Category.CategoryId == Model.Categories[j].CategoryId)
                    {
                        <li class=" list-group-item clearfix">
                            <label asp-for="@Model.Questions[i].Question" class="form-control-label font-weight-bold"></label> : @Html.DisplayFor(m => m.Questions[i].Question)
                            @if (Model.Questions[i].Type == QuestionType.Standard)
                        {
                                <br /><label class="form-control-label font-weight-bold">Answers:</label>
                                    <ul class="remove-left-padding">
                                        @foreach (var answer in Model.Questions[i].StandardAnswers)
                                        {
                                            <li class=" list-group-item remove-left-padding">
                                                <textarea readonly="readonly" rows="1" class="form-control autosize" asp-for="@answer"></textarea>
                                            </li>
                                        }
                                    </ul>
                            }
                            @if (Model.Questions[i].Type == QuestionType.Rate)
                        {
                                <div>
                                    <div class="form-group row">
                                        <label class="col-lg-4 font-weight-bold topMargin">Number of Votes: @Html.DisplayFor(m => m.Questions[i].RateAnswers.Count)</label>
                                        <div class="col-lg-8 row">
                                            <label class="font-weight-bold col-sm-3 topMargin">Average:</label>
                                            <input data-min="0" data-max="5" data-step="0.1" data-size="xs" data-display-only="true" asp-for="@Model.Questions[i].Average" class="rating rating-loading col-sm-9" />
                                        </div>
                                    </div>
                                    <a href="#@Collapse@j@i" data-toggle="collapse" aria-expanded="True" class="font-weight-bold"> Toggle vote distribution chart </a>
                                    <div id="@Collapse@j@i" class="collapsing">
                                        <div class="" id="@Chart@j@i"></div>
                                    </div>
                                    <script type="text/javascript">
                                    new Chartist.Bar('#@Chart@j@i',
                                        {
                                            labels:
                                                @Html.Raw(JsonConvert.SerializeObject(Model.Questions[i].LabelsList)),
                                            series: [
                                                @Html.Raw(JsonConvert.SerializeObject(Model.Questions[i].RatingsList))
                                            ]
                                        },
                                        {
                                            chartPadding: {
                                                top: 30,
                                                right: 0,
                                                bottom: 30,
                                                left: 20
                                            },
                                            stretch: true,
                                            height: 400,
                                            axisY: {
                                                onlyInteger: true
                                            },
                                            plugins: [
                                                Chartist.plugins.ctAxisTitle({
                                                    axisX: {
                                                        axisTitle: 'Score / Rating',
                                                        axisClass: 'font-weight-bold form-control-label',
                                                        offset: {
                                                            x: 0,
                                                            y: 50
                                                        },
                                                        textAnchor: 'middle'
                                                    },
                                                    axisY: {
                                                        axisTitle: 'Number of Votes',
                                                        axisClass: 'font-weight-bold form-control-label',
                                                        offset: {
                                                            x: 0,
                                                            y: -15
                                                        },
                                                        textAnchor: 'middle',
                                                        flipTitle: false
                                                    }
                                                })
                                            ]
                                        });
                                    </script>
                                </div>
                            }
                        </li>
                    }
                }
            </ul>
        }
    </div>
    <input type="hidden" asp-for="YearId" />
    <div class="row">
        <div class="col-xs-12">
            <br />
            <a asp-action="Details" asp-controller="Years" asp-route-id="@Model.YearId" class="float-xs-right">Back to Year form</a>
        </div>
    </div>
</div>

src/SoCFeedback/Views/Modules/Questions.cshtml
@model Module
@using Microsoft.AspNetCore.Authorization
@using SoCFeedback.Enums
@inject IAuthorizationService AuthorizationService
@{
    ViewData["Title"] = "Module Questions";
}

<form asp-action="Questions">
    <div>
            <h2>Module Questions</h2>
            <h4>Module</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Code)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Code)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Title)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Title)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Level)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Level.Title)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Supervisor)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Supervisor.FullName)
                </dd>
            </dl>
    <div class="row">
        <div class="col-md-12">
            <hr />
            <h4>Questions</h4>
            <br />
            @for (var j = 0; j < Model.Categories.Count; j++)
            {
                <input asp-for="@Model.Categories[j].Id" type="hidden" />
                <input type="hidden" asp-for="@Model.Categories[j].Title" />
                <span class=" text-primary h4 form-text">
                    @Html.DisplayFor(m => m.Categories[j].Title)
                </span>
                <ul class="list-group">
                    @for (var i = 0; i < Model.Questions.Count; i++)
                    {
                        if (Model.Questions[i].CategoryId == Model.Categories[j].Id)
                        {
                            var temp = Model.Questions[i].Optional.ToString();
                            <li class=" list-group-item col-md-12 clearfix">
                                @Html.HiddenFor(m => m.Questions[i].Id) @Html.HiddenFor(m => m.Questions[i].Question1) @Html.HiddenFor(m => m.Questions[i].Type)
                                @Html.HiddenFor(m => m.Questions[i].CategoryId) @Html.HiddenFor(m => m.Questions[i].Optional)
                                <label asp-for="@Model.Questions[i].Optional" class="form-control-label font-weight-bold"></label>: <span class="text-danger">@Html.DisplayFor(model => temp)</span>,
                                <label asp-for="@Model.Questions[i].Type" class="form-control-label font-weight-bold"></label> : <span class="text-primary">@Html.DisplayFor(m => m.Questions[i].Type)</span>,
                                <label asp-for="@Model.Questions[i].Question1" class="form-control-label font-weight-bold"></label> : @Html.DisplayFor(m => m.Questions[i].Question1)
                                @if (await AuthorizationService.AuthorizeAsync(User, "LecturerLimited"))
                                {
                                   if (Model.Questions[i].Optional == false)
                                    {

                                        <input asp-for="@Model.Questions[i].RunningStatus" asp-items="Html.GetEnumSelectList<RunningStatus>()" class="text-danger float-xs-right font-weight-bold readonly text-xs-right" readonly="readonly" />

                                    }
                                    else
                                    {
                                        <select asp-for="@Model.Questions[i].RunningStatus" asp-items="Html.GetEnumSelectList<RunningStatus>()" class="float-xs-right"></select>
                                    }
                                }
                                else
                                {
                                    <select asp-for="@Model.Questions[i].RunningStatus" asp-items="Html.GetEnumSelectList<RunningStatus>()" class="float-xs-right"></select>
                                }
                            </li>
                        }
                    }
                </ul>
            }
        </div>
        </div>
        <input type="hidden" asp-for="YearId" />
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <br />
            <input type="submit" value="Save" class="btn btn-primary" />
            <a asp-action="Details" asp-controller="Years" asp-route-id="@Model.YearId" class="float-xs-right">Back to Year form</a>
        </div>
    </div>
</form>